# Generated by Django 4.0.5 on 2023-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('affiliation', models.CharField(max_length=255)),
                ('citations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArxivPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('abstract', models.TextField()),
                ('summary', models.TextField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='images')),
                ('publication_date', models.DateField()),
                ('arxiv_id', models.CharField(max_length=20, unique=True)),
                ('authors', models.ManyToManyField(to='backend.author')),
                ('categories', models.ManyToManyField(to='backend.category')),
            ],
        ),
    ]
