# Generated by Django 4.0.5 on 2023-06-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_author_email_alter_author_affiliation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Subject',
        ),
    ]
