# Generated by Django 4.0.5 on 2023-06-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_categories_arxivpaper_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxivpaper',
            name='primary_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.subject'),
        ),
        migrations.AlterField(
            model_name='arxivpaper',
            name='subjects',
            field=models.ManyToManyField(related_name='papers', to='backend.subject'),
        ),
    ]
