# Generated by Django 4.0.5 on 2023-06-11 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_arxivpaper_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arxivpaper',
            name='source',
        ),
        migrations.AddField(
            model_name='arxivpaper',
            name='source_tar',
            field=models.FileField(blank=True, null=True, upload_to='tar_sources'),
        ),
        migrations.AddField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='arxivpaper',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots'),
        ),
        migrations.CreateModel(
            name='PaperSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.arxivpaper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.arxivpaper')),
            ],
        ),
        migrations.AddField(
            model_name='arxivpaper',
            name='images',
            field=models.ManyToManyField(related_name='paper_images', to='backend.paperimage'),
        ),
        migrations.AddField(
            model_name='arxivpaper',
            name='sources',
            field=models.ManyToManyField(related_name='paper_sources', to='backend.papersource'),
        ),
    ]
