# Generated by Django 4.0.5 on 2023-06-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_author_email_domain_author_scolar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='scolar_id',
            new_name='scholar_id',
        ),
    ]
