# Generated by Django 4.0.5 on 2023-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_scolar_id_author_scholar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxivpaper',
            name='total_author_citations',
            field=models.IntegerField(default=0),
        ),
    ]
