# Generated by Django 4.0.5 on 2023-06-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_arxivpaper_total_author_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arxivpaper',
            name='abstract',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='arxivpaper',
            name='summary',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='arxivpaper',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='arxivpaper',
            name='total_author_citations',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliation',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='citations',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='email_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
