# Generated by Django 4.0.5 on 2023-06-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_arxivpaper_abstract_alter_arxivpaper_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arxivpaper',
            name='citations',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
